OVC_IMS/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ovc_main import view_dashboard
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'ovc_home.views.ovc_login', name='ovc_login'),
    url(r'^change_password/', 'ovc_home.views.change_password', name='change_password'),
    url(r'^logout/', 'ovc_home.views.ovc_logout', name='ovc_logout'),
    url(r'^allocate_role/', 'ovc_home.views.allocate_role', name='allocate_role'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^home/', include('ovc_home.urls')),
    url(r'^organisation/', include('ovc_main.urls')),
    url(r'^workforce/', include('ovc_main.urls')),
    url(r'^beneficiary/', include('ovc_main.urls')),
    url(r'^capture/', include('ovc_main.urls')),
    url(r'^api/', include('ovc_main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', view_dashboard.report_counts, name='report_counts'),
    url(r'^dashboard_children/', view_dashboard.dashboard_children, name='dashboard_children'),
    #RapidSMS
    url(r'^sms/', include('ovc_sms.urls')),
)

ovc_main/urls.py
'''
Created on Sep 2, 2014

@author: MLumpa
'''
from django.conf.urls import patterns, url

from ovc_main import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^new/', views.new_organisation, name='new-organisation'),
    url(r'^wards/', views.listofwards, name='listofwards'),
    url(r'^orglists/', views.org_search_results, name='org_search_results'),
    url(r'^view_org/', views.organisation_view, name='organisation_view'),
    url(r'^update_org/', views.update_organisation, name='organisation_update'),
    url(r'^wfcsearch/', views.workforce_index, name='wfc_search_index'),
    url(r'^wfclists/', views.wfc_search_results, name='wfc_search_index'),
    url(r'^new_workforce/', views.new_workforce, name='workforce'),
    url(r'^orgautocomp/', views.org_autocompletion_list, name='orgautocomplete'),
    url(r'^view_wfc/', views.workforce_view, name='workforce_view'),
    url(r'^update_wfc/', views.workforce_update, name='workforce_update'),
    url(r'^communities/', views.list_of_cwacs_in_ward, name='list_of_cwacs_in_ward'),
    url(r'^ben_search/', views.search_beneficiary, name='ben_search'),
    url(r'^guardian/', views.new_guardian_reg, name='guardian'),
    url(r'^child/', views.new_child_reg, name='child'),
    url(r'^ben_autocomplete/', views.ben_autocompletion_list, name='benautocomplete'),
    url(r'^ben_wfc_autocomplete/', views.ben_wfc_autocompletion_list, name='benwfcautocomplete'),
    url(r'^ben_res_autocomplete/', views.ben_res_autocompletion_list, name='benresautocomplete'),
    url(r'^benlists/', views.ben_search_results, name='ben_search_results'),
    url(r'^view_ben/', views.beneficiary_view, name='beneficiary_view'),
    url(r'^update_ben/', views.update_beneficiary, name='beneficiary_update'),
    url(r'^guardian_contact/', views.get_guardian_contacts, name='guard_contact'),
    url(r'^capture_admin/', views.capture_admin, name='capture_administration'),
    url(r'^begin_upload/', views.start_upload, name='start_upload'),
    url(r'^begin_download/', views.start_download, name='start_download'),
    url(r'^upload/', views.process_upload, name='api_capture_upload'),
    url(r'^download/', views.download, name='download_sections'),
    #url(r'^persons/', views.get_persons_list, name='api_persons_list'),
)

ovc_auth/models.py
from django.db import models
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.models import BaseUserManager,AbstractBaseUser, PermissionsMixin, Group, Permission
from ovc_main.models import RegPerson, RegOrgUnit, RegPersonsGeo
from datetime import datetime
from django.db.models.fields.related import RelatedField



  
class OVCUserManager(BaseUserManager):

    def _create_user(self, workforce_id, password,
                     is_staff, is_superuser, **extra_fields):
        now = datetime.now()
        if not workforce_id:
            raise ValueError('The given workforce ID must be set')

        user = self.model(workforce_id=workforce_id,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, workforce_id, password=None, **extra_fields):
        return self._create_user(workforce_id, password, False, False,
                                 **extra_fields)

    def create_superuser(self, workforce_id, password, **extra_fields):
        return self._create_user(workforce_id, password, True, True,
                                 **extra_fields)

class AppUser(AbstractBaseUser, PermissionsMixin):
    reg_person = models.ForeignKey(RegPerson, null=True)
    workforce_id = models.CharField(max_length=8, unique=True)
    national_id = models.CharField(max_length=15, null=True)
    
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    
    allow_access = models.BooleanField(default=True)
    
    date_joined = models.DateTimeField(auto_now_add=True)
    
    timestamp_created = models.DateTimeField(auto_now_add=True)
    timestamp_updated = models.DateTimeField(auto_now=True)
    
    password_changed_timestamp = models.DateTimeField(null=True)
    
    objects = OVCUserManager()
    
    USERNAME_FIELD = 'workforce_id'
    REQUIRED_FIELDS = []
    
    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'
        db_table = 'auth_user'
        
    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name
    
    
    
    
class OVCPermission(Permission):
    permission_id = models.IntegerField(unique=True)
    permission_description = models.CharField(max_length=255)
    permission_set = models.CharField(max_length=100)
    permission_type = models.CharField(max_length=50, blank=True)
    restricted_to_self = models.BooleanField(blank=True, default=False)
    restricted_to_org_unit = models.BooleanField(blank=True, default=False)
    restricted_to_geo = models.BooleanField(blank=True, default=False)
    
    class Meta:
        db_table = 'auth_permission_detail'

class OVCRole(Group):
    group_id = models.CharField(max_length=5)
    group_name = models.CharField(max_length=100)
    group_description = models.CharField(max_length=255)
    restricted_to_org_unit = models.BooleanField(blank=True, default=False)
    restricted_to_geo  = models.BooleanField(blank=True,default=False)
    automatic  = models.BooleanField(default=False)
    class Meta:
        db_table = 'auth_group_detail'
    
class OVCUserRoleGeoOrg(models.Model):
    user = models.ForeignKey(AppUser)
    group = models.ForeignKey(OVCRole)
    org_unit = models.ForeignKey(RegOrgUnit, null=True)
    area = models.ForeignKey(RegPersonsGeo, null=True)
    void = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'auth_user_groups_geo_org'
    
    
    
    
    

ovc_main/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class RegOrgUnit(models.Model):
    unit_id = models.CharField(max_length=12)
    unit_name = models.CharField(max_length=255)
    unit_type_id = models.CharField(max_length=4)
    is_gdclsu  = models.BooleanField()
    date_operational = models.DateField(null=True)
    date_closed = models.DateField(null=True)
    is_void = models.BooleanField(default=False)
    parent_org_unit_id = models.CharField(max_length=12, null=True, blank=True)

    
    def _is_active(self):
        if self.date_closed:
            return False
        else:
            return True
    
    is_active = property(_is_active)
    
    class Meta:
        db_table = 'tbl_reg_org_units'
        
    def make_void(self, date_closed=None):
        self.is_void = True
        if date_closed:
            self.date_closed = date_closed
        super(RegOrgUnit, self).save()
    
    
    
class RegOrgUnitContact(models.Model):
    #organisation_unit_id = models.CharField(max_length=7)
    organisation = models.ForeignKey(RegOrgUnit)
    contact_detail_type_id = models.CharField(max_length=20)
    contact_detail = models.CharField(max_length=255)
    is_void = models.BooleanField(default=False)
    class Meta:
        db_table = 'tbl_reg_org_units_contact'
    
class RegOrgUnitExternalID(models.Model):
    #organisation_unit_id = models.CharField(max_length=7)
    organisation = models.ForeignKey(RegOrgUnit)
    identifier_type_id = models.CharField(max_length=4)
    identifier_value = models.CharField(max_length=255, null=True)
    is_void = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'tbl_reg_org_units_external_ids'
    
class RegOrgUnitGdclsu(models.Model):
    #organisation_unit_id = models.CharField(max_length=7)
    organisation = models.ForeignKey(RegOrgUnit)
    gdclsu_id = models.CharField(max_length=12)
    date_linked = models.DateField(null=True)
    date_delinked = models.DateField(null=True)
    is_void = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'tbl_reg_org_units_gdclsu'
    
class RegOrgUnitGeography(models.Model):
    #org_unit_id = models.CharField(max_length=7)
    organisation = models.ForeignKey(RegOrgUnit)
    area_id = models.IntegerField()
    date_linked = models.DateField(null=True)
    date_delinked = models.DateField(null=True)
    is_void = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'tbl_reg_org_units_geo'
        
    def make_void(self, date_delinked=None):
        self.is_void = True
        if date_delinked:
            self.date_delinked = date_delinked
        elif not self.date_delinked:
            self.date_delinked = datetime.now().date()
        super(RegOrgUnitGeography, self).save()
    
class RegPerson(models.Model):
    #person_id = models.CharField(primary_key=True,max_length=32)
    beneficiary_id = models.CharField(max_length=10, null=True, blank=True)
    workforce_id = models.CharField(max_length=8, null=True, blank=True)
    birth_reg_id = models.CharField(max_length=15, null=True, blank=True)
    national_id = models.CharField(max_length=15, null=True, blank=True)
    first_name = models.CharField(max_length=255)
    other_names = models.CharField(max_length=255, null=True, blank=True)
    surname = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    date_of_death = models.DateField(null=True, blank=True)
    sex_id = models.CharField(max_length=4)
    is_void = models.BooleanField(default=False)
    
    def _get_full_name(self):
        return self.first_name +' '+ self.other_names + ' ' + self.surname
    
    def make_void(self):
        self.is_void = True
        super(RegPerson,self).save()
    
    def record_death(self,date_of_death=None):
        if date_of_death:
            self.date_of_death = date_of_death
        super(RegPerson,self).save()
        
    full_name  = property(_get_full_name)
    class Meta:
        db_table = 'tbl_reg_persons'   
    
class SetupGeorgraphy(models.Model):
    area_id = models.IntegerField()
    area_type_id = models.CharField(max_length=50)
    area_name = models.CharField(max_length=100)
    parent_area_id = models.IntegerField(null=True)
    area_name_abbr = models.CharField(max_length=5, null=True)
    timestamp_created = models.DateTimeField(auto_now_add=True, default=datetime.now())
    timestamp_updated = models.DateTimeField(auto_now=True, default=datetime.now())
    is_void = models.BooleanField(default=False)
    class Meta:
        db_table = 'tbl_list_geo'
    
class SetupList(models.Model):
    item_id = models.CharField(max_length=4)
    item_description = models.CharField(max_length=255)
    item_description_short = models.CharField(max_length=26, null=True)
    item_category = models.CharField(max_length=255, null=True, blank=True)
    the_order = models.IntegerField(null=True)
    user_configurable = models.BooleanField(blank=True)
    sms_keyword = models.BooleanField(blank=True)
    is_void = models.BooleanField(default=False)
    field_name = models.CharField(max_length=200, null=True, blank=True)
    class Meta:
        db_table = 'tbl_list_general'

class AdminPreferences(models.Model):
    person = models.ForeignKey(RegPerson)
    preference_id = models.CharField(max_length=4)
    
    class Meta:
        db_table = 'tbl_admin_preferences'


class RegPersonsGuardians(models.Model):
    child_person = models.ForeignKey(RegPerson)
    guardian_person_id = models.CharField(max_length=10)
    relationship_notes = models.CharField(max_length=255)
    date_linked = models.DateField(null=True)
    date_delinked = models.DateField(null=True)
    is_void = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'tbl_reg_persons_guardians'
    
class RegPersonsTypes(models.Model):
    person = models.ForeignKey(RegPerson)
    person_type_id = models.CharField(max_length=4)
    date_began = models.DateField(null=True)
    date_ended = models.DateField(null=True)
    is_void = models.BooleanField(default=False)
    
    def make_void(self,person_type_change_date=None):
        self.is_void = True
        if person_type_change_date:
            if person_type_change_date < self.date_began:
                person_type_change_date = datetime.now().date()
            self.date_ended = person_type_change_date
        super(RegPersonsTypes,self).save()
        
    class Meta:
        db_table = 'tbl_reg_persons_types'
    
class RegPersonsGeo(models.Model):
    person = models.ForeignKey(RegPerson)
    area_id = models.IntegerField()
    date_linked = models.DateField(null=True)
    date_delinked = models.DateField(null=True)
    is_void = models.BooleanField(default=False)
    
    def make_void(self,date_delinked, is_void):
        if date_delinked:
            if date_delinked < self.date_linked:
                date_delinked = datetime.now().date()
        self.date_delinked=date_delinked
        self.is_void=True
        super(RegPersonsGeo,self).save()
        
    class Meta:
        db_table = 'tbl_reg_persons_geo'

class RegPersonsGdclsu(models.Model):
    person = models.ForeignKey(RegPerson)
    gdclsu = models.ForeignKey(RegOrgUnit)
    date_linked = models.DateField(null=True)
    date_delinked = models.DateField(null=True)
    is_void = models.BooleanField(default=False)
    
    def make_void(self,date_delinked, is_void=True):
        if date_delinked:
            if date_delinked < self.date_linked:
                date_delinked = datetime.now().date()
        self.date_delinked=date_delinked
        self.is_void=True
        super(RegPersonsGdclsu,self).save()
        
    class Meta:
        db_table = 'tbl_reg_persons_gdclsu'
        
class RegPersonsExternalIds(models.Model):
    person = models.ForeignKey(RegPerson)
    identifier_type_id = models.CharField(max_length=4)
    identifier = models.CharField(max_length=255)
    is_void = models.BooleanField(default=False)
    
    def make_void(self):
        self.is_void = True
        super(RegPersonsExternalIds,self).save()
        
    class Meta:
        db_table = 'tbl_reg_persons_external_ids'

class RegPersonsContact(models.Model):
    person = models.ForeignKey(RegPerson)
    contact_detail_type_id = models.CharField(max_length=4)
    contact_detail = models.CharField(max_length=255)
    is_void = models.BooleanField(default=False)
    
    def make_void(self):
        self.is_void = True
        super(RegPersonsContact,self).save()

    class Meta:
        db_table = 'tbl_reg_persons_contact'

class RegPersonsOrgUnits(models.Model):
    person = models.ForeignKey(RegPerson)
    parent_org_unit = models.ForeignKey(RegOrgUnit)
    primary = models.IntegerField()
    date_linked = models.DateField(null=True)
    date_delinked = models.DateField(null=True)
    is_void = models.BooleanField(default=False)
    
    def make_void(self,parent_org_change_date=None):
        self.is_void = True
        if parent_org_change_date:
            if parent_org_change_date < self.date_linked:
                parent_org_change_date = datetime.now().date()
            self.date_delinked = parent_org_change_date
        super(RegPersonsOrgUnits,self).save()
        
    class Meta:
        db_table = 'tbl_reg_persons_org_units'
        
class CoreAdverseConditions(models.Model):
    beneficiary_id = models.CharField(max_length=15)
    adverse_condition_id = models.CharField(max_length=4)
    is_void = models.IntegerField(null=True)
    sms_id = models.IntegerField(null=True)
    form_id = models.IntegerField(null=True)
    
    class Meta:
        db_table = 'tbl_core_adverse_conditions'
        
class FormResChildren(models.Model):
    child_beneficiary_id = models.CharField(max_length=15)
    institution_id = models.CharField(max_length=12)
    form_id = models.CharField(max_length=128, null=True)
    sms_id = models.IntegerField(null=True)

ovc_main/templates/ovc_main/new_workforce.html
{% extends "main_base.html" %}
{% load crispy_forms_tags %}
{% block page_title %}{{ app_name }} | Workforce {% endblock %}
{% block navbar_class_dashboard %}{% endblock %}
{% block navbar_class_registries %}active{% endblock %}
{% block navbar_class_workforce %}active{% endblock %}


{% block body_page_title %} <i class="fa fa-user fa-4"></i>  {{page_title}} {% endblock %}
{% block breadcrum %}
<li class="hidden"><a href="#">New Workforce</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
<li>New Workforce</li>
{% endblock breadcrum %}


{% block content %}

<div class="container">
    <div class="row">

        {% crispy form %}
    </div>
</div>




<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>	
<script>
$(document).ready(function () {
    if ($("#id_date_of_death").val() == '') {
        $("#div_id_date_of_death").hide();
    }
    $('.datepicker').datepicker(
            {
                //minDate: "-18Y",
                dateFormat: 'd-MM-yy',
                yearRange: "1904:2050",
                maxDate: 0,
                changeMonth: true,
                changeYear: true
            });

    $("input[id='id_edit_mode']").on('ifChecked', function () {
        var selVal = $(this).val();
        if (selVal == 2)
        {
            $("#div_id_date_of_death").show();
        }
        else
        {
            $("#div_id_date_of_death").hide();
            $("#id_date_of_death").val('');
        }
    });
});
//TODO add the default year -18Y
</script>
{% endblock content %}

ovc_main/templates/ovc_main/workforce_view_readonly.html
{% extends "main_base.html" %}
{% load crispy_forms_tags %}
{% block page_title %}{{ app_name }} | Workforce Member {% endblock %}
{% block navbar_class_dashboard %}{% endblock %}
{% block navbar_class_registries %}active{% endblock %}
{% block navbar_class_workforce %}active{% endblock %}

{% block body_page_title %} View Details - Workforce{% endblock %}
{% block breadcrum %}
<li class="hidden"><a href="#">Workforce Member - View Details</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
<li>Workforce Member - View Details</li>
{% endblock breadcrum %}
{% block content %}
<div class="form-horizontal">
    <div class="note note-info">
        <h4><strong>Workforce Member - View Details</strong></h4>
    </div></p>

<div class="multiField">
    <div class="panel panel-grey" >
        <div class="panel-body pan" ><p/> 
            <div id="div_id_workforce_id" class="form-group">
                <label for="id_workforce_id" class="control-label col-md-3">Workforce member ID:</label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.workforce_id}}</strong></p>
                </div>

            </div>
            <div id="div_id_national_id" class="form-group">
                <label for="id_national_id" class="control-label col-md-3">NRC:</label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.national_id}}</strong></p>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-pink" >
        <div class="panel-heading" >
            Personal Details
        </div>
        <div class="panel-body pan" ><p/> 
            <div id="div_id_first_name" class="form-group">
                <label for="id_first_name" class="control-label col-md-3">First Name: </label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.first_name}}</strong></p>
                </div>

            </div>
            <div id="div_id_surname" class="form-group">
                <label for="id_surname" class="control-label col-md-3">Surname: </label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.surname}}</strong></p>
                </div>
            </div>
            <div id="div_id_other_names" class="form-group">
                <label for="id_other_names" class="control-label col-md-3">Other name(s): </label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.other_names}}</strong></p>
                </div>
            </div>
            <div id="div_id_sex" class="form-group">
                <label for="id_sex" class="control-label col-md-3">Sex: </label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.sex}}</strong></p>
                </div>

            </div>
            <div id="div_id_date_of_birth" class="form-group">
                <label for="id_date_of_birth" class="control-label col-md-3">Date of birth:</label>
                <div class="col-md-6">
                    {% if workforce.date_of_birth %}
                    <p class="form-control-static"><strong>{{workforce.date_of_birth}}</strong></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-grey" >
        <div class="panel-heading" >
            Workforce Type
        </div>

        <div class="panel-body pan" ><p/> 
            <div id="div_id_workforce_type" class="form-group">
                <label for="id_organisation_type" class="control-label col-md-3">workforce_type: </label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.person_type}}</strong></p>
                </div>

            </div>
            <div id="div_id_man_number" class="form-group">
                <label for="id_man_number" class="control-label col-md-3">
                    MAN number:</label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.man_number}}</strong></p>
                </div>
            </div>
            <div id="div_id_ts_number" class="form-group">
                <label for="id_ts_number" class="control-label col-md-3">
                    If teacher, TS number:</label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.ts_number}}</strong></p>
                </div>
            </div>
            <div id="div_id_sign_number" class="form-group">
                <label for="id_sign_number" class="control-label col-md-3">
                    If police officer, Sign number:</label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.sign_number}}</strong></p>
                </div>
            </div>
            <div id="div_id_steps_ovc_number" class="form-group">
                <label for="id_steps_ovc_number" class="control-label col-md-3">
                    STEPS OVC number: 
                </label>
                <div class="col-md-6">
                    <p class="form-control-static"><strong>{{workforce.steps_ovc_number}}</strong></p>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-pink" >
        <div class="panel-heading" >
            Parent Organisational Unit(s)
        </div>
        <div class="panel-body" ><p/> 
            <table id="orgTable"  class="table table-hover table-condensed">
                <thead>
                    <tr>
                        <th>Org Unit</th>
                        <th>Org unit ID</th>
                        <th>Primary parent org unit</th>
                        <th>Registration assistant for the organization</th>
                    </tr>
                    {% for org in workforce.org_units%}
                    <tr>
                        <td>{{ org.org_name }}</td>
                        <td>{{ org.org_id }}</td>
                        <td>{{ org.primary_org }}</td>
                        <td>{{ org.is_reg_assistant }}</td>
                    </tr>
                    {% endfor %}
                </thead>
                <tbody>

                </tbody>
            </table>

        </div>
    </div>
</div>
<div class="panel panel-grey" >
    <div class="panel-heading" >
        Where do you work?:
    </div>
    <div class="panel-body" ><p/> 
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Province-District</th>
                    <th>Constituency-Ward</th>
                    <th>Community ( CWAC or GDCLSU)</th>
                </tr>
            </thead>
            <tbody>
                {% for locationprovided in workforce.locations_for_display %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    {% for individuallocation in locationprovided %}

                    {% if forloop.counter0 == 0 %}
                    <td>{{individuallocation.geoname}}
                        {% endif %}
                        {% if forloop.counter0 == 1 %}
                        -{{individuallocation.geoname}}</td>
                    {% endif %}
                    {% if forloop.counter0 == 2 %}
                    <td>{{individuallocation.geoname}}
                        {% endif %}
                        {% if forloop.counter0 == 3 %}
                        -{{individuallocation.geoname}}</td>
                    {% endif %}
                    {% if forloop.counter0 == 4 %}
                    <td>{{individuallocation.geoname}}</td>
                    {% endif %}
                    {% if forloop.counter0 == 1 and forloop.last %}
                    <td>n/a</td>
                    <td>n/a</td>
                    {% endif %}
                    {% if forloop.counter0 == 2 and forloop.last %}
                    <td>n/a</td>
                    {% endif %}
                    {% if forloop.counter0 == 3 and forloop.last %}
                    <td>n/a</td>
                    {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %} 

            </tbody>
        </table>
    </div>
</div>
<div class="panel panel-pink" >
    <div class="panel-heading" >
        Contact Details:
    </div>
    <div class="panel-body pan" ><p/> 
        <div id="id_designated_phone_number" class="form-group">
            <label for="id_designated_phone_number" class="control-label col-md-3">
                Designated mobile number for sending and receiving SMSes:
            </label>
            <div class="col-md-6">
                <p class="form-control-static"><strong>{{workforce.contact.designated_phone_number}}</strong></p>
            </div>
        </div>
        <div id="div_id_mobile_phone_number" class="form-group">
            <label for="id_other_mobile_number" class="control-label col-md-3">
                Other mobile number: 
            </label>
            <div class="col-md-6">
                <p class="form-control-static"><strong>{{workforce.contact.other_mobile_number}}</strong></p>
            </div>
        </div>
        <div id="div_id_email_address" class="form-group">
            <label for="id_email_address" class="control-label col-md-3">
                Email address:
            </label>
            <div class="col-md-6">
                <p class="form-control-static"><strong>{{workforce.contact.email_address}}</strong></p>
            </div>
        </div>
        <div id="div_id_physical_address" class="form-group">
            <label for="id_physical_address" class="control-label col-md-3">
                Physical address:
            </label>
            <div class="col-md-6">
                <p class="form-control-static"><strong>{{workforce.contact.physical_address}}</strong></p>
            </div>
        </div>
    </div>
</div>
<div class="md-col-6" style="margin-left:41%">
    <span style="display:{{sec.user_can_edit}}"><a type="button" href="/workforce/update_wfc?person_id={{workforce.id_int}}" class="btn btn-primary"><i class="fa fa-pencil-square-o"></i> Update...</a></span>
    <span><a type="button" href="/workforce/wfcsearch/" class="btn btn-success"><i class="fa fa-arrow-circle-o-left"></i> Go Back</a></span>
    <span style="display:{{sec.user_can_assign_role}}"><a type="button" href="/allocate_role?workforceid={{workforce.id_int}}" class="btn btn-warning"><i class="fa fa-arrow-circle-o-left"></i> Allocate Role</a></span>
</div>
</div>
{% endblock content %}